[package]
name = "vesting"
version = "0.0.0"
authors = ["Constantin Dogaru"]
edition = "2018"
publish = false

[lib]
path = "src/vesting.rs"

[dependencies.multiversx-sc]
version = "0.47.4"

[dev-dependencies.multiversx-sc-scenario]
version = "0.47.4"

[dev-dependencies]
num-bigint = "0.4.2"
