[package]
name = "empty"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[lib]
path = "src/empty.rs"

[dependencies.elrond-wasm]
version = "0.29.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.0"

[dev-dependencies]
num-bigint = "0.4.2"
