[package]
name = "staking"
version = "0.0.0"
authors = ["Constantin Dogaru <ctin.dogaru95@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/staking.rs"

[dependencies.multiversx-sc]
version = "0.39.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.2"
